(source gnu)
(source melpa)

; Cask deps
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "expand-region")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "popwin")
(depends-on "projectile")
(depends-on "s")
(depends-on "smex")
(depends-on "wrap-region")
(depends-on "yasnippet")

; My deps
(depends-on "coffee-mode")
(depends-on "flycheck")
(depends-on "git-gutter")
(depends-on "grizzl")
(depends-on "haskell-mode")
(depends-on "js2-mode")
(depends-on "less-css-mode")
(depends-on "less-css-mode")
(depends-on "php-mode")
(depends-on "rust-mode")
(depends-on "web-mode")
(depends-on "yaml-mode")
